# Generated by Django 4.1.7 on 2023-03-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_emp_code_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
    ]
