# Generated by Django 4.1.7 on 2023-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='0831112222', max_length=15),
            preserve_default=False,
        ),
    ]
